
#ifndef _WINGUI_H_
#define _WINGUI_H_


#define WM_VLCSTREAMUSER		(WM_USER+2000)
#define WM_TOUCHIN				(WM_VLCSTREAMUSER+0)
#define WM_MCTRLNEXTTRACK		(WM_VLCSTREAMUSER+10)
#define WM_WAKEUP				(WM_VLCSTREAMUSER+20)
#define WM_ADDTRACKINIT			(WM_VLCSTREAMUSER+30)
#define WM_ADDTRACKCHAR			(WM_VLCSTREAMUSER+31)

#define WM_CDS_ADDTRACK			(WM_VLCSTREAMUSER+40)		// add track/path to root
#define WM_CDS_ADDTRACK_DSP		(WM_VLCSTREAMUSER+41)		// to whichever playlist is displayed in Album (shelf) view
#define WM_CDS_ADDTRACK_PLY		(WM_VLCSTREAMUSER+42)		// to queued (playing) playlist
#define WM_CDS_CMDCTRL			(WM_VLCSTREAMUSER+43)

#define WM_MWHEELFORWARD		(WM_VLCSTREAMUSER+50)
#define WM_MWHEELBACK			(WM_VLCSTREAMUSER+51)
#define WM_MWHEEL_FORWARD		(WM_MWHEELFORWARD)
#define WM_MWHEEL_BACK			(WM_MWHEELBACK)
#define WM_MWHEEL_LEFT			(WM_VLCSTREAMUSER+52)
#define WM_MWHEEL_RIGHT			(WM_VLCSTREAMUSER+53)
#define WM_MEDIA_CHANGE			(WM_VLCSTREAMUSER+60)
#define WM_VAUDIO_DEV_CHANGE	(WM_VLCSTREAMUSER+70)
#define WM_VAUDIO_VOL_CHANGE	(WM_VLCSTREAMUSER+71)
#define WM_HOOKPOINTER			(WM_VLCSTREAMUSER+80)
#define WM_EXTCMD				(WM_VLCSTREAMUSER+90)
#define WM_TRAY_HOOK			(WM_VLCSTREAMUSER+100)
#define WM_SHELL_HOOK			(WM_VLCSTREAMUSER+101)
#define WM_SYSTRAY				(WM_VLCSTREAMUSER+200)
#define WM_TRACKPLAYNOTIFY		(WM_VLCSTREAMUSER+201)
#define WM_TRACKTIMESTAMPNOTIFY	(WM_VLCSTREAMUSER+202)
#define WM_TRACKCHAPTERUPDATE	(WM_VLCSTREAMUSER+203)

#define WM_MM					(WM_VLCSTREAMUSER+2000)
#define WM_DD_MOUSEACTIVATE  	(WM_MM+WM_MOUSEACTIVATE)
#define WM_DD_MOUSEMOVE	    	(WM_MM+WM_MOUSEMOVE)
#define WM_DD_LBUTTONDOWN	   	(WM_MM+WM_LBUTTONDOWN)
#define WM_DD_LBUTTONUP	    	(WM_MM+WM_LBUTTONUP)
#define WM_DD_LBUTTONDBLCLK   	(WM_MM+WM_LBUTTONDBLCLK)
#define WM_DD_RBUTTONDOWN	   	(WM_MM+WM_RBUTTONDOWN)
#define WM_DD_RBUTTONUP	    	(WM_MM+WM_RBUTTONUP)
#define WM_DD_RBUTTONDBLCLK   	(WM_MM+WM_RBUTTONDBLCLK)
#define WM_DD_MBUTTONDOWN	   	(WM_MM+WM_MBUTTONDOWN)
#define WM_DD_MBUTTONUP	    	(WM_MM+WM_MBUTTONUP)
#define WM_DD_MBUTTONDBLCLK   	(WM_MM+WM_MBUTTONDBLCLK)
#define WM_DD_MOUSEWHEEL	   	(WM_MM+WM_MOUSEWHEEL)
#define WM_DD_MOUSEHWHEEL	   	(WM_MM+WM_MOUSEHWHEEL)
#define WM_DD_MOUSEHOVER	   	(WM_MM+WM_MOUSEHOVER)
#define WM_DD_MOUSELEAVE	   	(WM_MM+WM_MOUSELEAVE)
#define WM_DD_NCMOUSEHOVER		(WM_MM+WM_NCMOUSEHOVER)
#define WM_DD_NCMOUSELEAVE		(WM_MM+WM_NCMOUSELEAVE)
#define WM_DD_CHARDOWN			(WM_MM+WM_CHAR)
#define WM_DD_KEYDOWN			(WM_MM+WM_KEYDOWN)
#define WM_DD_CLOSE				(WM_MM+WM_CLOSE)

#define WM_DD_MINIMZE			(0xF020)
#define WM_DD_MAXIMIZE			(0xF030)
#define WM_DD_RESTORE			(0xF120)

#define WM_ADDCH				(WM_MM+1000)


#define MOUSE_CAP_OFF			(0)
#define MOUSE_CAP_ON			(1)


int startMouseCapture ();
void endMouseCapture ();

int winuiGetWindowState ();
void winuiMenuUpdate ();



#endif

